package com.mathvision.util;

import com.mathvision.model.Narrative;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Shared utilities for GeoGebra command post-processing and static prechecks.
 */
public final class GeoGebraCodeUtils {

    private GeoGebraCodeUtils() {}

    public static final String EXPECTED_FIGURE_NAME = "GeoGebraFigure";

    private static final String SCENE_DIRECTIVE_LINE_PREFIX = "# @scene ";
    private static final String SCENE_BUTTONS_BEGIN_MARKER = "# AUTOGEN_SCENE_BUTTONS_BEGIN";
    private static final String SCENE_BUTTONS_END_MARKER = "# AUTOGEN_SCENE_BUTTONS_END";

    private static final Pattern FULL_WIDTH_PUNCTUATION = Pattern.compile(
            "[\\uFF0C\\uFF1B\\uFF1A\\u3002\\uFF01\\uFF1F\\uFF08\\uFF09"
                    + "\\u3010\\u3011\\u300A\\u300B\\u201C\\u201D\\u2018\\u2019]");

    private static final Pattern ASSIGNMENT_OR_NAMED_OBJECT = Pattern.compile(
            "^([A-Za-z][A-Za-z0-9_'{}]*)\\s*[:=]\\s*(.+)$");

    private static final Pattern COMMAND_CALL = Pattern.compile(
            "^([A-Za-z][A-Za-z0-9_'{}]*)\\s*\\(.*\\)$");

    private static final Pattern GEOGEBRA_COMMAND_CALL = Pattern.compile(
            "\\b([A-Z][A-Za-z0-9_]*)\\s*\\(");

    public static final class SceneDirective {
        public String id;
        public String title;
        public List<String> show = new ArrayList<>();
        public List<String> hide = new ArrayList<>();
    }

    public static String extractCode(String response) {
        if (response == null || response.isBlank()) {
            return "";
        }
        String extracted = JsonUtils.extractCodeBlock(response);
        if (extracted != null && !extracted.isBlank()) {
            return extracted;
        }
        return response.trim();
    }

    public static List<String> extractCommands(String geoGebraCode) {
        String normalized = extractCode(geoGebraCode);
        List<String> commands = new ArrayList<>();
        for (String line : normalized.split("\\R")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("#") || trimmed.startsWith("//")) {
                continue;
            }
            commands.add(trimmed);
        }
        return commands;
    }

    public static String enrichWithSceneButtons(String geoGebraCode, Narrative.Storyboard storyboard) {
        String normalized = extractCode(geoGebraCode);
        List<String> strippedLines = stripAutoGeneratedSceneDirectiveLines(normalized);
        String baseScript = String.join("\n", strippedLines).trim();
        List<SceneDirective> directives = extractSceneDirectives(normalized);
        if (directives.isEmpty()) {
            directives = buildSceneDirectives(storyboard);
        }
        return appendSceneDirectives(baseScript, directives);
    }

    public static List<SceneDirective> extractSceneDirectives(String geoGebraCode) {
        List<SceneDirective> directives = new ArrayList<>();
        if (geoGebraCode == null || geoGebraCode.isBlank()) {
            return directives;
        }

        for (String line : geoGebraCode.split("\\R")) {
            String trimmed = line.trim();
            if (!trimmed.startsWith(SCENE_DIRECTIVE_LINE_PREFIX)) {
                continue;
            }
            String json = trimmed.substring(SCENE_DIRECTIVE_LINE_PREFIX.length()).trim();
            if (json.isEmpty()) {
                continue;
            }
            directives.add(JsonUtils.fromJson(json, SceneDirective.class));
        }
        return directives;
    }

    public static List<String> validateStructure(String geoGebraCode) {
        List<String> violations = new ArrayList<>();
        if (geoGebraCode == null || geoGebraCode.isBlank()) {
            violations.add("Code is empty");
            return violations;
        }

        List<String> commands = extractCommands(geoGebraCode);
        if (commands.isEmpty()) {
            violations.add("No executable GeoGebra commands found");
            return violations;
        }

        return violations;
    }

    public static List<String> validateGeoGebraRules(String geoGebraCode) {
        List<String> violations = new ArrayList<>();
        if (geoGebraCode == null || geoGebraCode.isBlank()) {
            return violations;
        }

        String punctuationEvidence = CodeValidationSupport.findFirstMatchEvidence(geoGebraCode, FULL_WIDTH_PUNCTUATION);
        if (punctuationEvidence != null) {
            violations.add("Contains full-width punctuation that GeoGebra command parsing may reject"
                    + " (" + punctuationEvidence + ")");
        }

        String multiCommandEvidence = findFirstSemicolonEvidence(extractCommands(geoGebraCode));
        if (multiCommandEvidence != null) {
            violations.add("Contains multiple commands on one line; keep one GeoGebra command per line"
                    + " (" + multiCommandEvidence + ")");
        }

        String undocumentedCommandEvidence = findFirstUndocumentedGeoGebraCommandCall(geoGebraCode);
        if (undocumentedCommandEvidence != null) {
            violations.add("Static rule violation: undocumented GeoGebra command"
                    + " (" + undocumentedCommandEvidence + ")");
        }

        return violations;
    }

    public static List<String> validateFull(String geoGebraCode) {
        List<String> violations = new ArrayList<>();
        violations.addAll(validateStructure(geoGebraCode));
        violations.addAll(validateGeoGebraRules(geoGebraCode));
        return violations;
    }

    public static boolean looksLikeCommandBlock(String geoGebraCode) {
        List<String> commands = extractCommands(geoGebraCode);
        if (commands.isEmpty()) {
            return false;
        }

        int commandLikeLines = 0;
        for (String command : commands) {
            if (looksLikeCommand(command)) {
                commandLikeLines++;
            }
        }
        return commandLikeLines * 2 >= commands.size();
    }

    public static boolean looksLikeCommand(String command) {
        if (command == null || command.isBlank()) {
            return false;
        }
        return ASSIGNMENT_OR_NAMED_OBJECT.matcher(command).matches()
                || COMMAND_CALL.matcher(command).matches();
    }

    private static String findFirstSemicolonEvidence(List<String> commands) {
        for (int i = 0; i < commands.size(); i++) {
            String command = commands.get(i);
            if (command.contains(";")) {
                return "line " + (i + 1) + ": " + abbreviate(command);
            }
        }
        return null;
    }

    static String findFirstUndocumentedGeoGebraCommandCall(String geoGebraCode) {
        List<String> commands = extractCommands(geoGebraCode);
        Set<String> documented = GeoGebraValidationSupport.documentedCommandNames();
        for (int i = 0; i < commands.size(); i++) {
            String command = stripDoubleQuotedText(commands.get(i));
            Matcher matcher = GEOGEBRA_COMMAND_CALL.matcher(command);
            while (matcher.find()) {
                String commandName = matcher.group(1);
                if (!documented.contains(commandName)) {
                    return "line " + (i + 1) + ": " + commandName + "() - " + abbreviate(commands.get(i));
                }
            }
        }
        return null;
    }

    private static String stripDoubleQuotedText(String command) {
        if (command == null || command.isBlank()) {
            return "";
        }
        StringBuilder result = new StringBuilder(command.length());
        boolean inDoubleQuote = false;
        for (int i = 0; i < command.length(); i++) {
            char ch = command.charAt(i);
            char previous = i > 0 ? command.charAt(i - 1) : '\0';
            if (ch == '"' && previous != '\\') {
                inDoubleQuote = !inDoubleQuote;
                result.append(' ');
            } else {
                result.append(inDoubleQuote ? ' ' : ch);
            }
        }
        return result.toString();
    }

    private static boolean hasBalancedDelimiters(String command) {
        int parentheses = 0;
        int brackets = 0;
        int braces = 0;
        boolean inDoubleQuote = false;

        for (int i = 0; i < command.length(); i++) {
            char ch = command.charAt(i);
            char previous = i > 0 ? command.charAt(i - 1) : '\0';

            // In GeoGebra, ' (apostrophe) is the prime notation for object names
            // (e.g. A', B', AB') — not a string quote delimiter. Only " is used
            // for string literals, so we skip single-quote toggling entirely.
            if (ch == '"' && previous != '\\') {
                inDoubleQuote = !inDoubleQuote;
                continue;
            }
            if (inDoubleQuote) {
                continue;
            }

            if (ch == '(') {
                parentheses++;
            } else if (ch == ')') {
                parentheses--;
            } else if (ch == '[') {
                brackets++;
            } else if (ch == ']') {
                brackets--;
            } else if (ch == '{') {
                braces++;
            } else if (ch == '}') {
                braces--;
            }

            if (parentheses < 0 || brackets < 0 || braces < 0) {
                return false;
            }
        }

        return !inDoubleQuote
                && parentheses == 0
                && brackets == 0
                && braces == 0;
    }

    private static String abbreviate(String text) {
        if (text == null) {
            return "";
        }
        return text.length() > 120 ? text.substring(0, 120) + "..." : text;
    }

    private static List<String> stripAutoGeneratedSceneDirectiveLines(String geoGebraCode) {
        List<String> lines = new ArrayList<>();
        boolean insideAutogenBlock = false;
        for (String rawLine : extractCode(geoGebraCode).split("\\R", -1)) {
            String trimmed = rawLine.trim();
            if (SCENE_BUTTONS_BEGIN_MARKER.equals(trimmed)) {
                insideAutogenBlock = true;
                continue;
            }
            if (SCENE_BUTTONS_END_MARKER.equals(trimmed)) {
                insideAutogenBlock = false;
                continue;
            }
            if (!insideAutogenBlock && !trimmed.startsWith(SCENE_DIRECTIVE_LINE_PREFIX)) {
                lines.add(rawLine);
            }
        }
        while (!lines.isEmpty() && lines.get(lines.size() - 1).trim().isEmpty()) {
            lines.remove(lines.size() - 1);
        }
        return lines;
    }

    private static String appendSceneDirectives(String baseScript, List<SceneDirective> directives) {
        if (directives == null || directives.isEmpty()) {
            return baseScript;
        }

        StringBuilder sb = new StringBuilder(baseScript);
        if (!baseScript.isBlank()) {
            sb.append("\n\n");
        }
        sb.append(SCENE_BUTTONS_BEGIN_MARKER).append('\n');
        for (SceneDirective directive : directives) {
            sb.append(SCENE_DIRECTIVE_LINE_PREFIX)
                    .append(JsonUtils.toJson(directive))
                    .append('\n');
        }
        sb.append(SCENE_BUTTONS_END_MARKER);
        return sb.toString();
    }

    private static List<SceneDirective> buildSceneDirectives(Narrative.Storyboard storyboard) {
        List<SceneDirective> directives = new ArrayList<>();
        if (storyboard == null || storyboard.getScenes() == null || storyboard.getScenes().isEmpty()) {
            return directives;
        }

        Set<String> allObjectIds = new LinkedHashSet<>();
        for (Narrative.StoryboardScene scene : storyboard.getScenes()) {
            if (scene == null) {
                continue;
            }
            for (Narrative.StoryboardObject object : scene.getEnteringObjects()) {
                if (object != null && object.getId() != null && !object.getId().isBlank()) {
                    allObjectIds.add(object.getId().trim());
                }
            }
            allObjectIds.addAll(StoryboardPatchResolver.idsOf(scene.getPersistentObjects()));
            allObjectIds.addAll(StoryboardPatchResolver.idsOf(scene.getExitingObjects()));
        }

        int fallbackIndex = 1;
        for (Narrative.StoryboardScene scene : storyboard.getScenes()) {
            if (scene == null) {
                fallbackIndex++;
                continue;
            }
            LinkedHashSet<String> visible = new LinkedHashSet<>();
            visible.addAll(StoryboardPatchResolver.idsOf(scene.getPersistentObjects()));
            for (Narrative.StoryboardObject object : scene.getEnteringObjects()) {
                if (object != null && object.getId() != null && !object.getId().isBlank()) {
                    visible.add(object.getId().trim());
                }
            }
            visible.removeAll(StoryboardPatchResolver.idsOf(scene.getExitingObjects()));
            if (visible.isEmpty()) {
                fallbackIndex++;
                continue;
            }

            LinkedHashSet<String> hidden = new LinkedHashSet<>(allObjectIds);
            hidden.removeAll(visible);

            SceneDirective directive = new SceneDirective();
            directive.id = firstNonBlank(scene.getSceneId(), "scene_" + fallbackIndex);
            directive.title = buildSceneTitle(scene, fallbackIndex);
            directive.show = new ArrayList<>(visible);
            directive.hide = new ArrayList<>(hidden);
            directives.add(directive);
            fallbackIndex++;
        }

        return directives;
    }

    private static String buildSceneTitle(Narrative.StoryboardScene scene, int index) {
        String title = scene != null ? firstNonBlank(scene.getTitle(), scene.getGoal()) : null;
        if (title == null || title.isBlank()) {
            return "Scene " + index;
        }
        return title.trim();
    }

    private static String firstNonBlank(String first, String second) {
        if (first != null && !first.isBlank()) {
            return first.trim();
        }
        if (second != null && !second.isBlank()) {
            return second.trim();
        }
        return null;
    }

}
