package com.automanim.prompt;

/**
 * Central registry of all tool JSON schemas used for structured LLM output.
 *
 * Consolidates tool definitions previously scattered across node classes.
 */
public final class ToolSchemas {

    private ToolSchemas() {}

    // ========================================================================
    // Stage 0: Exploration
    // ========================================================================

    public static final String PREREQUISITES = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_prerequisites\","
            + "    \"description\": \"Return the list of direct prerequisite teaching beats.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"prerequisites\": {"
            + "          \"type\": \"array\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"step\": { \"type\": \"string\", \"description\": \"Short description of the prerequisite teaching beat\" },"
            + "              \"reason\": { \"type\": \"string\", \"description\": \"Why this prerequisite beat matters in the learning path\" }"
            + "            },"
            + "            \"required\": [\"step\", \"reason\"]"
            + "          }"
            + "        }"
            + "      },"
            + "      \"required\": [\"prerequisites\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String FOUNDATION_CHECK = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_foundation_decision\","
            + "    \"description\": \"Return whether the concept is already foundational enough.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"is_foundation\": { \"type\": \"boolean\", \"description\": \"Whether the concept should stop expanding\" },"
            + "        \"reason\": { \"type\": \"string\", \"description\": \"Short justification\" }"
            + "      },"
            + "      \"required\": [\"is_foundation\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String INPUT_MODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_input_mode\","
            + "    \"description\": \"Classify the workflow input mode.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"input_mode\": {"
            + "          \"type\": \"string\","
            + "          \"enum\": [\"concept\", \"problem\"],"
            + "          \"description\": \"Workflow mode for the input\""
            + "        },"
            + "        \"reason\": { \"type\": \"string\", \"description\": \"Short routing rationale\" }"
            + "      },"
            + "      \"required\": [\"input_mode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String PROBLEM_GRAPH = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_problem_step_graph\","
            + "    \"description\": \"Return a compact graph of animation-ready teaching beats for solving the problem.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"root_id\": { \"type\": \"string\", \"description\": \"Root node id\" },"
            + "        \"nodes\": {"
            + "          \"type\": \"array\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"id\": { \"type\": \"string\" },"
            + "              \"step\": { \"type\": \"string\" },"
            + "              \"reason\": { \"type\": \"string\", \"description\": \"Why this teaching beat matters\" },"
            + "              \"node_type\": { \"type\": \"string\" },"
            + "              \"min_depth\": { \"type\": \"integer\" },"
            + "              \"is_foundation\": { \"type\": \"boolean\" }"
            + "            },"
            + "            \"required\": [\"id\", \"step\", \"node_type\", \"min_depth\", \"is_foundation\"]"
            + "          }"
            + "        },"
            + "        \"prerequisite_edges\": {"
            + "          \"type\": \"object\","
            + "          \"additionalProperties\": {"
            + "            \"type\": \"array\","
            + "            \"items\": { \"type\": \"string\" }"
            + "          }"
            + "        }"
            + "      },"
            + "      \"required\": [\"root_id\", \"nodes\", \"prerequisite_edges\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1a: Math Enrichment
    // ========================================================================

    public static final String MATH_ENRICHMENT = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_enrichment\","
            + "    \"description\": \"Return mathematical enrichment for the concept.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"equations\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Key LaTeX formulas\""
            + "        },"
            + "        \"definitions\": {"
            + "          \"type\": \"object\","
            + "          \"additionalProperties\": { \"type\": \"string\" },"
            + "          \"description\": \"Term to definition mapping\""
            + "        },"
            + "        \"interpretation\": { \"type\": \"string\", \"description\": \"Intuitive explanation\" },"
            + "        \"examples\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Concrete examples\""
            + "        }"
            + "      },"
            + "      \"required\": [\"equations\", \"definitions\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1b: Visual Design
    // ========================================================================

    public static final String VISUAL_DESIGN = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_visual_spec\","
            + "    \"description\": \"Return visual design specification for the concept.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"layout\": { \"type\": \"string\", \"description\": \"Relative placement and main visible composition for world-space elements; do not use for overlay text\" },"
            + "        \"motion_plan\": { \"type\": \"string\", \"description\": \"Temporal evolution only: what appears, moves, transforms, or is emphasized over time, including transition style\" },"
            + "        \"scene_mode\": { \"type\": \"string\", \"enum\": [\"2d\", \"3d\"], \"description\": \"2d by default, 3d only when depth is needed\" },"
            + "        \"camera_plan\": { \"type\": \"string\", \"description\": \"Camera orientation or motion for 3d scenes\" },"
            + "        \"screen_overlay_plan\": { \"type\": \"string\", \"description\": \"Only text, formulas, counters, or UI-style annotations that stay fixed in frame\" },"
            + "        \"color_scheme\": { \"type\": \"string\", \"description\": \"Main colors and emphasis roles\" },"
            + "        \"duration\": { \"type\": \"number\", \"description\": \"Approximate seconds\" },"
            + "        \"color_palette\": { \"type\": \"array\", \"items\": { \"type\": \"string\" }, \"description\": \"Manim color names\" }"
            + "      },"
            + "      \"required\": [\"layout\", \"motion_plan\", \"color_scheme\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1c: Narrative
    // ========================================================================

    public static final String STORYBOARD = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_storyboard\","
            + "    \"description\": \"Return a structured storyboard for the animation.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"hook\": {"
            + "          \"type\": \"string\","
            + "          \"description\": \"Opening hook that frames the topic or problem and gives the first scene a clear narrative entry point\""
            + "        },"
            + "        \"summary\": {"
            + "          \"type\": \"string\","
            + "          \"description\": \"Brief overview of the storyboard arc, including what the animation teaches and how it progresses\""
            + "        },"
            + "        \"continuity_plan\": {"
            + "          \"type\": \"string\","
            + "          \"description\": \"How object identities, anchors, and layout remain stable across scenes so code generation can reuse mobjects safely\""
            + "        },"
            + "        \"global_visual_rules\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Global staging rules that should hold across the whole animation, such as safe-area, clutter, or continuity constraints\","
            + "          \"items\": { \"type\": \"string\" }"
            + "        },"
            + "        \"scenes\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Ordered scene plan. Each item is one executable storyboard beat with pacing, layout, object lifecycle, and animation actions.\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"scene_id\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Stable unique scene identifier such as scene_1, used for referencing and deterministic normalization\""
            + "              },"
            + "              \"title\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Short production title naming the scene's main beat\""
            + "              },"
            + "              \"goal\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"What the learner should understand or what solving progress should be achieved by the end of the scene\""
            + "              },"
            + "              \"narration\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Voiceover text or narration summary for this scene only\""
            + "              },"
            + "              \"duration_seconds\": {"
            + "                \"type\": \"integer\","
            + "                \"description\": \"Approximate scene duration in seconds for pacing and render planning\""
            + "              },"
            + "              \"scene_mode\": {"
            + "                \"type\": \"string\","
            + "                \"enum\": [\"2d\", \"3d\"],"
            + "                \"description\": \"Scene dimensionality. Use 3d only when depth is genuinely necessary to explain the idea\""
            + "              },"
            + "              \"camera_anchor\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Primary visual anchor or focus region the camera should center on\""
            + "              },"
            + "              \"camera_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Camera behavior for the scene, including static framing, pans, rotations, or viewpoint setup\""
            + "              },"
            + "              \"layout_goal\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Target screen composition describing where the main elements should sit relative to the frame and to each other\""
            + "              },"
            + "              \"safe_area_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"How important content remains inside the readable safe area and avoids edge collisions or overlap\""
            + "              },"
            + "              \"screen_overlay_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Any text, labels, or formulas that should stay fixed to screen space rather than move with the world\""
            + "              },"
            + "              \"geometry_constraints\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Scene-level hard geometric invariants that downstream stages must preserve, such as reflection symmetry, collinearity, equal-radius construction, incidence, bounded motion, or intersection definitions\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"step_refs\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Referenced teaching beats, graph nodes, or problem-solving steps covered by this scene\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"entering_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Objects first introduced in this scene. Each one should be concrete enough for code generation to instantiate and place.\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"id\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Stable object id used for continuity, transforms, and later references. Use ASCII camelCase or concise math-style identifiers only, with no underscores. Keep it short and non-redundant because `kind` already carries the type, for example `A`, `P`, `ABprime`, `aLabel` rather than `pointA`, `labelA`, or `A_label`\""
            + "                    },"
            + "                    \"kind\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Object category such as text, equation, axes, point, line, graph, label, region, or helper. Do not duplicate this type information inside `id`\""
            + "                    },"
            + "                    \"content\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Mathematical or visual content represented by the object. If it references other storyboard objects, mention them by id only and do not repeat their kind, for example `angle between AP and l at P` rather than `angle between segment AP and line l at point P`\""
            + "                    },"
            + "                    \"placement\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Explicit initial placement or layout intent relative to the frame or existing anchors, not vague styling language and not the only place to encode hard geometry\""
            + "                    },"
            + "                    \"style\": {"
            + "                      \"type\": \"array\","
            + "                      \"description\": \"Structured visual style layers. Use this only when non-default rendering guidance is needed.\","
            + "                      \"items\": {"
            + "                        \"type\": \"object\","
            + "                        \"properties\": {"
            + "                          \"role\": {"
            + "                            \"type\": \"string\","
            + "                            \"description\": \"Visual role such as text, background, border, glow, badge, or emphasis\""
            + "                          },"
            + "                          \"type\": {"
            + "                            \"type\": \"string\","
            + "                            \"description\": \"Implementation hint such as MathTex, Tex, Text, SurroundingRectangle, RoundedRectangle, BackgroundRectangle, or backend-specific drawable style type\""
            + "                          },"
            + "                          \"properties\": {"
            + "                            \"type\": \"object\","
            + "                            \"description\": \"Backend-relevant style properties such as color, font_size, fill_opacity, stroke_width, buff, corner_radius, line_style, label_visible, or z_index. Encode concrete rendering intent here instead of prose.\","
            + "                            \"additionalProperties\": true"
            + "                          }"
            + "                        },"
            + "                        \"required\": [\"role\", \"type\", \"properties\"]"
            + "                      }"
            + "                    },"
            + "                    \"source_node\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Originating knowledge node or solving step when relevant\""
            + "                    },"
            + "                    \"behavior\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Dependency role such as static, follows_anchor, derived, or fixed_overlay. This encodes how the object is defined or attached, not by itself whether the object is fixed or movable\""
            + "                    },"
            + "                    \"anchor_id\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Id of the object this one should stay attached to when relevant\""
            + "                    },"
            + "                    \"dependency_note\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Short note for update or attachment logic: what source objects define this object, what it follows, or how it should update. If other objects are mentioned, refer to them by id only and do not restate their kind\""
            + "                    },"
            + "                    \"constraint_note\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Hard local geometric rule for the object, such as lies on l, reflection of B across l, intersection of ABprime and l, or restricted to a segment/range. If other objects are mentioned, refer to them by id only\""
            + "                    }"
            + "                  },"
            + "                  \"required\": [\"id\", \"kind\", \"content\", \"placement\"]"
            + "                }"
            + "              },"
            + "              \"persistent_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Ids of objects already on screen that should remain visible and be reused in this scene\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"exiting_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Ids of objects removed in this scene to reduce clutter or conclude a beat\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"actions\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Ordered animation operations that describe how the scene unfolds on screen.\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"order\": {"
            + "                      \"type\": \"integer\","
            + "                      \"description\": \"Execution order of the action within the scene\""
            + "                    },"
            + "                    \"type\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Action category such as create, write, transform, highlight, move, fade_out, or camera\""
            + "                    },"
            + "                    \"targets\": {"
            + "                      \"type\": \"array\","
            + "                      \"description\": \"Ids of the objects mainly affected by the action\","
            + "                      \"items\": { \"type\": \"string\" }"
            + "                    },"
            + "                    \"description\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Concrete animation intent describing what visibly changes and why\""
            + "                    }"
            + "                  },"
            + "                  \"required\": [\"order\", \"type\", \"description\"]"
            + "                }"
            + "              },"
            + "              \"notes_for_codegen\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Extra implementation hints for the code generation stage, especially around continuity, transforms, or layout edge cases\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              }"
            + "            },"
            + "            \"required\": [\"scene_id\", \"title\", \"goal\", \"narration\", \"layout_goal\", \"safe_area_plan\", \"entering_objects\", \"persistent_objects\", \"exiting_objects\", \"actions\"]"
            + "          }"
            + "        }"
            + "      },"
            + "      \"required\": [\"scenes\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 2: Code Generation
    // ========================================================================

    public static final String MANIM_CODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_manim_code\","
            + "    \"description\": \"Return complete Manim Community Python animation code.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"code\": { \"type\": \"string\", \"description\": \"Complete Manim Python source code\" },"
            + "        \"scene_name\": { \"type\": \"string\", \"description\": \"Primary scene class name in ASCII\" },"
            + "        \"description\": { \"type\": \"string\", \"description\": \"Short summary of the animation\" }"
            + "      },"
            + "      \"required\": [\"code\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String GEOGEBRA_CODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_geogebra_code\","
            + "    \"description\": \"Return complete GeoGebra Classic command code.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"code\": { \"type\": \"string\", \"description\": \"Complete GeoGebra command script\" },"
            + "        \"figure_name\": { \"type\": \"string\", \"description\": \"Primary figure name in ASCII\" },"
            + "        \"description\": { \"type\": \"string\", \"description\": \"Short summary of the construction\" },"
            + "        \"artifact_format\": { \"type\": \"string\", \"description\": \"Output form such as commands\" }"
            + "      },"
            + "      \"required\": [\"code\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 3: Code Evaluation
    // ========================================================================

    public static final String CODE_REVIEW = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_code_review\","
            + "    \"description\": \"Return structured code review for Manim animation quality.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"approved_for_render\": { \"type\": \"boolean\", \"description\": \"Whether code is approved for render\" },"
            + "        \"layout_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"continuity_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"pacing_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"clutter_risk\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"likely_offscreen_risk\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"summary\": { \"type\": \"string\" },"
            + "        \"strengths\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "        \"blocking_issues\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "        \"revision_directives\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } }"
            + "      },"
            + "      \"required\": [\"approved_for_render\", \"layout_score\", \"continuity_score\", \"pacing_score\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";
}
