package com.mathvision.prompt;

/**
 * Central registry of all tool JSON schemas used for structured LLM output.
 *
 * Consolidates tool definitions previously scattered across node classes.
 */
public final class ToolSchemas {

    private ToolSchemas() {}

    // ========================================================================
    // Stage 0: Exploration
    // ========================================================================

    public static final String INPUT_MODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_input_mode\","
            + "    \"description\": \"Classify the workflow input mode.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"input_mode\": {"
            + "          \"type\": \"string\","
            + "          \"enum\": [\"concept\", \"problem\"],"
            + "          \"description\": \"Workflow mode for the input\""
            + "        },"
            + "        \"reason\": { \"type\": \"string\", \"description\": \"Short routing rationale\" }"
            + "      },"
            + "      \"required\": [\"input_mode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String CONCEPT_GRAPH = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_concept_graph\","
            + "    \"description\": \"Return a compact teaching DAG for explaining the concept.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"start_id\": { \"type\": \"string\", \"description\": \"Start node id\" },"
            + "        \"nodes\": {"
            + "          \"type\": \"array\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"id\": { \"type\": \"string\" },"
            + "              \"step\": { \"type\": \"string\" },"
            + "              \"reason\": { \"type\": \"string\", \"description\": \"Why this teaching beat matters\" },"
            + "              \"node_type\": { \"type\": \"string\", \"description\": \"One of concept, observation, construction, derivation, conclusion\" },"
            + "              \"min_depth\": { \"type\": \"integer\" },"
            + "              \"is_foundation\": { \"type\": \"boolean\" }"
            + "            },"
            + "            \"required\": [\"id\", \"step\", \"node_type\", \"min_depth\", \"is_foundation\"]"
            + "          }"
            + "        },"
            + "        \"next_edges\": {"
            + "          \"type\": \"object\","
            + "          \"additionalProperties\": {"
            + "            \"type\": \"array\","
            + "            \"items\": { \"type\": \"string\" }"
            + "          }"
            + "        },"
            + "        \"teaching_order\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Ordered list of node ids in the intended teaching/presentation sequence\""
            + "        }"
            + "      },"
            + "      \"required\": [\"start_id\", \"nodes\", \"next_edges\", \"teaching_order\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String PROBLEM_GRAPH = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_problem_step_graph\","
            + "    \"description\": \"Return a compact graph of presentation-ready teaching beats for solving the problem.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"start_id\": { \"type\": \"string\", \"description\": \"Start node id\" },"
            + "        \"nodes\": {"
            + "          \"type\": \"array\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"id\": { \"type\": \"string\" },"
            + "              \"step\": { \"type\": \"string\" },"
            + "              \"reason\": { \"type\": \"string\", \"description\": \"Why this teaching beat matters\" },"
            + "              \"node_type\": { \"type\": \"string\", \"description\": \"One of problem, observation, construction, derivation, conclusion\" },"
            + "              \"min_depth\": { \"type\": \"integer\" },"
            + "              \"is_foundation\": { \"type\": \"boolean\" }"
            + "            },"
            + "            \"required\": [\"id\", \"step\", \"node_type\", \"min_depth\", \"is_foundation\"]"
            + "          }"
            + "        },"
            + "        \"next_edges\": {"
            + "          \"type\": \"object\","
            + "          \"additionalProperties\": {"
            + "            \"type\": \"array\","
            + "            \"items\": { \"type\": \"string\" }"
            + "          }"
            + "        },"
            + "        \"teaching_order\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Ordered list of node ids in the intended teaching/presentation sequence\""
            + "        }"
            + "      },"
            + "      \"required\": [\"start_id\", \"nodes\", \"next_edges\", \"teaching_order\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1a: Math Enrichment
    // ========================================================================

    public static final String MATH_ENRICHMENT = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_enrichment\","
            + "    \"description\": \"Return mathematical enrichment for the concept.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"equations\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Key LaTeX formulas\""
            + "        },"
            + "        \"definitions\": {"
            + "          \"type\": \"object\","
            + "          \"additionalProperties\": { \"type\": \"string\" },"
            + "          \"description\": \"Term to definition mapping\""
            + "        },"
            + "        \"interpretation\": { \"type\": \"string\", \"description\": \"Intuitive explanation\" },"
            + "        \"examples\": {"
            + "          \"type\": \"array\","
            + "          \"items\": { \"type\": \"string\" },"
            + "          \"description\": \"Concrete examples\""
            + "        }"
            + "      },"
            + "      \"required\": [\"equations\", \"definitions\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1c: Storyboard Validation
    // ========================================================================

    public static final String STORYBOARD = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_storyboard\","
            + "    \"description\": \"Return a structured storyboard for the presentation.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"

            + "        \"continuity_plan\": {"
            + "          \"type\": \"string\","
            + "          \"description\": \"How object identities, anchors, and layout remain stable across scenes so downstream code generation can reuse the same logical objects safely\""
            + "        },"
            + "        \"global_visual_rules\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Global staging rules that should hold across the whole presentation, such as safe-area, clutter, empty-space, hierarchy, or continuity constraints\","
            + "          \"items\": { \"type\": \"string\" }"
            + "        },"
            + "        \"object_registry\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Canonical global object definitions. Keep identity, content, dependency, and behavior here; do not include scene-specific placement.\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"description\": \"Each learner-visible object has a unique id, a kind, and content. Mention objects by id only elsewhere; do not restate their kind or content.\","
            + "            \"properties\": {"
            + "              \"id\": { \"type\": \"string\" },"
            + "              \"kind\": { \"type\": \"string\" },"
            + "              \"content\": { \"type\": \"string\" },"
            + "              \"source_node\": { \"type\": \"string\" },"
            + "              \"behavior\": { \"type\": \"string\", \"enum\": [\"static\", \"follows_anchor\", \"derived\", \"fixed_overlay\"], \"description\": \"Use `fixed_overlay` mainly for explanatory text or annotations that should stay in screen space rather than native geometry\" },"
            + "              \"anchor_id\": { \"type\": \"string\" },"
            + "              \"dependency_note\": { \"type\": \"string\" },"
            + "              \"constraint_note\": { \"type\": \"string\" }"
            + "            },"
            + "            \"additionalProperties\": false,"
            + "            \"required\": [\"id\", \"kind\", \"content\"]"
            + "          }"
            + "        },"
            + "        \"scenes\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Ordered scene plan. Each item is one learner-visible teaching beat with pacing, layout, object lifecycle, and scene actions.\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"scene_id\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Stable unique scene identifier such as scene_1, used for referencing and deterministic normalization\""
            + "              },"
            + "              \"title\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Short production title naming the scene's main beat\""
            + "              },"
            + "              \"goal\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"What the learner should understand or what solving progress should be achieved by the end of the scene\""
            + "              },"
            + "              \"narration\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Voiceover text or narration summary for this scene only. Its sentences should align with visible beats\""
            + "              },"
            + "              \"duration_seconds\": {"
            + "                \"type\": \"integer\","
            + "                \"description\": \"Approximate scene duration in seconds for pacing and render planning\""
            + "              },"
            + "              \"scene_mode\": {"
            + "                \"type\": \"string\","
            + "                \"enum\": [\"2d\", \"3d\"],"
            + "                \"description\": \"Scene dimensionality. Use 3d only when depth is genuinely necessary to explain the idea\""
            + "              },"
            + "              \"camera_anchor\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Primary visual anchor or focus region the camera should center on\""
            + "              },"
            + "              \"camera_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Camera behavior for the scene, including static framing, pans, rotations, or viewpoint setup\""
            + "              },"
            + "              \"layout_goal\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Target screen composition describing the main focus, relative placement, and intended empty breathing room for the scene\""
            + "              },"
            + "              \"safe_area_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"How important content remains inside the readable safe area, avoids edge collisions or overlap, and preserves room for later reveals when needed\""
            + "              },"
            + "              \"screen_overlay_plan\": {"
            + "                \"type\": \"string\","
            + "                \"description\": \"Any text, labels, or formulas that should stay fixed to screen space rather than move with the world, including the intended safe overlay zone\""
            + "              },"
            + "              \"geometry_constraints\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Scene-level hard geometric invariants that downstream stages must preserve, such as reflection symmetry, collinearity, equal-radius construction, incidence, bounded motion, or intersection definitions\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"step_refs\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Referenced teaching beats, graph nodes, or problem-solving steps covered by this scene\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              },"
            + "              \"entering_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Scene patches for newly entering objects. Raw storyboard entries should contain `id` plus optional `placement` and `style` only.\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"id\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Stable object id used for continuity, transforms, and later references.\""
            + "                    },"
            + "                    \"placement\": {"
            + "                      \"type\": \"object\","
            + "                      \"description\": \"Structured placement patch with coordinate_space plus optional x/y/z value or min/max.\","
            + "                      \"properties\": {"
            + "                        \"coordinate_space\": { \"type\": \"string\", \"enum\": [\"world\", \"screen\", \"anchor\"] },"
            + "                        \"x\": { \"type\": \"object\", \"properties\": { \"value\": { \"type\": \"number\" }, \"min\": { \"type\": \"number\" }, \"max\": { \"type\": \"number\" } }, \"additionalProperties\": false },"
            + "                        \"y\": { \"type\": \"object\", \"properties\": { \"value\": { \"type\": \"number\" }, \"min\": { \"type\": \"number\" }, \"max\": { \"type\": \"number\" } }, \"additionalProperties\": false },"
            + "                        \"z\": { \"type\": \"object\", \"properties\": { \"value\": { \"type\": \"number\" }, \"min\": { \"type\": \"number\" }, \"max\": { \"type\": \"number\" } }, \"additionalProperties\": false }"
            + "                      },"
            + "                      \"additionalProperties\": false"
            + "                    },"
            + "                    \"style\": {"
            + "                      \"type\": \"array\","
            + "                      \"description\": \"Structured visual style layers. Use this only when non-default rendering guidance is needed.\","
            + "                      \"items\": {"
            + "                        \"type\": \"object\","
            + "                        \"properties\": {"
            + "                          \"role\": {"
            + "                            \"type\": \"string\","
            + "                            \"enum\": [\"text\", \"background\", \"border\", \"glow\", \"badge\", \"emphasis\", \"helper\"],"
            + "                            \"description\": \"Visual role such as text, background, border, glow, badge, or emphasis\""
            + "                          },"
            + "                          \"type\": {"
            + "                            \"type\": \"string\","
            + "                            \"enum\": [\"math_text\", \"plain_text\", \"background_box\", \"border_box\", \"highlight_ring\"],"
            + "                            \"description\": \"Implementation hint for the visual layer, preferably backend-neutral names such as math_text, plain_text, background_box, border_box, or highlight_ring\""
            + "                          },"
            + "                          \"properties\": {"
            + "                            \"type\": \"object\","
            + "                            \"description\": \"Backend-relevant style properties such as color, font_size, fill_opacity, stroke_width, padding, corner_radius, line_style, label_visible, or z_index. Encode concrete rendering intent here instead of prose.\","
            + "                            \"properties\": {"
            + "                              \"color\": { \"type\": \"string\" },"
            + "                              \"fill_color\": { \"type\": \"string\" },"
            + "                              \"stroke_color\": { \"type\": \"string\" },"
            + "                              \"line_style\": { \"type\": \"string\" },"
            + "                              \"font_size\": { \"type\": \"number\" },"
            + "                              \"stroke_width\": { \"type\": \"number\" },"
            + "                              \"padding\": { \"type\": \"number\" },"
            + "                              \"corner_radius\": { \"type\": \"number\" },"
            + "                              \"z_index\": { \"type\": \"number\" },"
            + "                              \"opacity\": { \"type\": \"number\" },"
            + "                              \"fill_opacity\": { \"type\": \"number\" },"
            + "                              \"stroke_opacity\": { \"type\": \"number\" },"
            + "                              \"label_visible\": { \"type\": \"boolean\" }"
            + "                            },"
            + "                            \"patternProperties\": {"
            + "                              \"^.*_color$\": { \"type\": \"string\" }"
            + "                            },"
            + "                            \"additionalProperties\": {"
            + "                              \"type\": [\"string\", \"number\", \"boolean\", \"array\", \"object\", \"null\"]"
            + "                            }"
            + "                          }"
            + "                        },"
            + "                        \"additionalProperties\": false,"
            + "                        \"required\": [\"role\", \"type\", \"properties\"]"
            + "                      }"
            + "                    }"
            + "                  },"
            + "                  \"additionalProperties\": false,"
            + "                  \"required\": [\"id\"]"
            + "                }"
            + "              },"
            + "              \"persistent_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Scene patches for objects already on screen that should remain visible and be reused in this scene. Raw storyboard entries should contain `id` plus optional changed `placement` and `style` only.\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"id\": { \"type\": \"string\" },"
            + "                    \"placement\": { \"type\": \"object\" },"
            + "                    \"style\": { \"type\": \"array\", \"items\": { \"type\": \"object\" } }"
            + "                  },"
            + "                  \"additionalProperties\": false,"
            + "                  \"required\": [\"id\"]"
            + "                }"
            + "              },"
            + "              \"exiting_objects\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Id-only entries for objects removed in this scene to reduce clutter, clear temporary annotations, or conclude a beat\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"id\": { \"type\": \"string\" }"
            + "                  },"
            + "                  \"additionalProperties\": false,"
            + "                  \"required\": [\"id\"]"
            + "                }"
            + "              },"
            + "              \"actions\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Ordered scene or presentation operations that describe how the scene unfolds on screen. Each action should correspond to one learner-visible beat or one small grouped beat.\","
            + "                \"items\": {"
            + "                  \"type\": \"object\","
            + "                  \"properties\": {"
            + "                    \"order\": {"
            + "                      \"type\": \"integer\","
            + "                      \"description\": \"Execution order of the action within the scene\""
            + "                    },"
            + "                    \"type\": {"
            + "                      \"type\": \"string\","
            + "                      \"enum\": [\"create\", \"write\", \"transform\", \"highlight\", \"move\", \"fade_out\", \"camera\", \"restyle\"],"
            + "                      \"description\": \"Action category such as create, write, transform, highlight, move, fade_out, or camera\""
            + "                    },"
            + "                    \"targets\": {"
            + "                      \"type\": \"array\","
            + "                      \"description\": \"Ids of the objects mainly affected by the action; mention them by id only, e.g. 'angle between AP and l at P' — do not restate their kind or content\","
            + "                      \"items\": { \"type\": \"string\" }"
            + "                    },"
            + "                    \"description\": {"
            + "                      \"type\": \"string\","
            + "                      \"description\": \"Concrete presentation intent describing what visibly changes, what the learner should notice, and why\""
            + "                    }"
            + "                  },"
            + "                  \"additionalProperties\": false,"
            + "                  \"required\": [\"order\", \"type\", \"description\"]"
            + "                }"
            + "              },"
            + "              \"notes_for_codegen\": {"
            + "                \"type\": \"array\","
            + "                \"description\": \"Extra implementation hints for the code generation stage, especially around continuity, transforms, or layout edge cases\","
            + "                \"items\": { \"type\": \"string\" }"
            + "              }"
            + "            },"
            + "            \"additionalProperties\": false,"
            + "            \"required\": [\"scene_id\", \"title\", \"goal\", \"narration\", \"layout_goal\", \"safe_area_plan\", \"entering_objects\", \"persistent_objects\", \"exiting_objects\", \"actions\"]"
            + "          }"
            + "        }"
            + "      },"
            + "      \"additionalProperties\": false,"
            + "      \"required\": [\"scenes\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 2: Code Generation
    // ========================================================================

    public static final String MANIM_CODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_manim_code\","
            + "    \"description\": \"Return complete Manim Community Python animation code.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"manimCode\": { \"type\": \"string\", \"description\": \"Complete Manim Python source code\" },"
            + "        \"scene_name\": { \"type\": \"string\", \"description\": \"Primary scene class name in ASCII\" },"
            + "        \"description\": { \"type\": \"string\", \"description\": \"Short summary of the animation\" }"
            + "      },"
            + "      \"required\": [\"manimCode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String GEOGEBRA_CODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_geogebra_code\","
            + "    \"description\": \"Return complete GeoGebra Classic command code.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"geogebraCode\": { \"type\": \"string\", \"description\": \"Complete GeoGebra command script\" },"
            + "        \"figure_name\": { \"type\": \"string\", \"description\": \"Primary figure name in ASCII\" },"
            + "        \"description\": { \"type\": \"string\", \"description\": \"Short summary of the construction\" },"
            + "        \"artifact_format\": { \"type\": \"string\", \"description\": \"Output form such as commands\" }"
            + "      },"
            + "      \"required\": [\"geogebraCode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 1b (scene-level): Scene Design
    // ========================================================================

    /**
     * Tool schema for per-node scene design output.
     * Returns a single StoryboardScene plus new_objects to add to the global registry.
     * Scene properties are a subset of the STORYBOARD scenes.items schema.
     */
    public static final String SCENE_DESIGN = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_scene_design\","
            + "    \"description\": \"Return a storyboard scene design for this knowledge node, plus any new objects to register globally.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"scene\": {"
            + "          \"type\": \"object\","
            + "          \"description\": \"A single StoryboardScene for this node.\","
            + "          \"properties\": {"
            + "            \"scene_id\": { \"type\": \"string\" },"
            + "            \"title\": { \"type\": \"string\" },"
            + "            \"goal\": { \"type\": \"string\" },"
            + "            \"narration\": { \"type\": \"string\" },"
            + "            \"duration_seconds\": { \"type\": \"integer\" },"
            + "            \"scene_mode\": { \"type\": \"string\", \"enum\": [\"2d\", \"3d\"] },"
            + "            \"camera_anchor\": { \"type\": \"string\" },"
            + "            \"camera_plan\": { \"type\": \"string\" },"
            + "            \"layout_goal\": { \"type\": \"string\" },"
            + "            \"safe_area_plan\": { \"type\": \"string\" },"
            + "            \"screen_overlay_plan\": { \"type\": \"string\" },"
            + "            \"geometry_constraints\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "            \"step_refs\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "            \"entering_objects\": {"
            + "              \"type\": \"array\","
            + "              \"items\": {"
            + "                \"type\": \"object\","
            + "                \"properties\": {"
            + "                  \"id\": { \"type\": \"string\" },"
            + "                  \"placement\": {"
            + "                    \"type\": \"object\","
            + "                    \"properties\": {"
            + "                      \"coordinate_space\": { \"type\": \"string\", \"enum\": [\"world\", \"screen\", \"anchor\"] },"
            + "                      \"x\": { \"type\": \"object\" },"
            + "                      \"y\": { \"type\": \"object\" },"
            + "                      \"z\": { \"type\": \"object\" }"
            + "                    },"
            + "                    \"additionalProperties\": false"
            + "                  },"
            + "                  \"style\": { \"type\": \"array\", \"items\": { \"type\": \"object\" } }"
            + "                },"
            + "                \"additionalProperties\": false,"
            + "                \"required\": [\"id\"]"
            + "              }"
            + "            },"
            + "            \"persistent_objects\": {"
            + "              \"type\": \"array\","
            + "              \"description\": \"Scene patches for objects already on screen that should remain visible. Each entry carries `id` plus optional changed `placement`/`style` only.\","
            + "              \"items\": {"
            + "                \"type\": \"object\","
            + "                \"properties\": {"
            + "                  \"id\": { \"type\": \"string\" },"
            + "                  \"placement\": {"
            + "                    \"type\": \"object\","
            + "                    \"properties\": {"
            + "                      \"coordinate_space\": { \"type\": \"string\", \"enum\": [\"world\", \"screen\", \"anchor\"] },"
            + "                      \"x\": { \"type\": \"object\" },"
            + "                      \"y\": { \"type\": \"object\" },"
            + "                      \"z\": { \"type\": \"object\" }"
            + "                    },"
            + "                    \"additionalProperties\": false"
            + "                  },"
            + "                  \"style\": { \"type\": \"array\", \"items\": { \"type\": \"object\" } }"
            + "                },"
            + "                \"additionalProperties\": false,"
            + "                \"required\": [\"id\"]"
            + "              }"
            + "            },"
            + "            \"exiting_objects\": {"
            + "              \"type\": \"array\","
            + "              \"description\": \"Id-only entries for objects removed in this scene.\","
            + "              \"items\": {"
            + "                \"type\": \"object\","
            + "                \"properties\": { \"id\": { \"type\": \"string\" } },"
            + "                \"additionalProperties\": false,"
            + "                \"required\": [\"id\"]"
            + "              }"
            + "            },"
            + "            \"actions\": {"
            + "              \"type\": \"array\","
            + "              \"description\": \"Ordered scene operations describing how the scene unfolds on screen.\","
            + "              \"items\": {"
            + "                \"type\": \"object\","
            + "                \"properties\": {"
            + "                  \"order\": { \"type\": \"integer\", \"description\": \"Execution order within the scene\" },"
            + "                  \"type\": { \"type\": \"string\", \"enum\": [\"create\", \"write\", \"transform\", \"highlight\", \"move\", \"fade_out\", \"camera\", \"restyle\"], \"description\": \"Action category\" },"
            + "                  \"targets\": { \"type\": \"array\", \"items\": { \"type\": \"string\" }, \"description\": \"Object ids affected by the action\" },"
            + "                  \"description\": { \"type\": \"string\", \"description\": \"What visibly changes and why\" }"
            + "                },"
            + "                \"additionalProperties\": false,"
            + "                \"required\": [\"order\", \"type\", \"description\"]"
            + "              }"
            + "            },"
            + "            \"notes_for_codegen\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } }"
            + "          },"
            + "          \"required\": [\"scene_id\", \"title\", \"goal\", \"narration\", \"layout_goal\", \"safe_area_plan\", \"entering_objects\", \"persistent_objects\", \"exiting_objects\", \"actions\"]"
            + "        },"
            + "        \"new_objects\": {"
            + "          \"type\": \"array\","
            + "          \"description\": \"Full definitions of objects introduced in this scene that should be added to the global object registry.\","
            + "          \"items\": {"
            + "            \"type\": \"object\","
            + "            \"properties\": {"
            + "              \"id\": { \"type\": \"string\" },"
            + "              \"kind\": { \"type\": \"string\" },"
            + "              \"content\": { \"type\": \"string\" },"
            + "              \"source_node\": { \"type\": \"string\" },"
            + "              \"behavior\": { \"type\": \"string\" },"
            + "              \"anchor_id\": { \"type\": \"string\" },"
            + "              \"dependency_note\": { \"type\": \"string\" },"
            + "              \"constraint_note\": { \"type\": \"string\" }"
            + "            },"
            + "            \"required\": [\"id\", \"kind\", \"content\"]"
            + "          }"
            + "        }"
            + "      },"
            + "      \"required\": [\"scene\", \"new_objects\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================
    // Stage 2 (scene-level): Skeleton + Per-Scene Code
    // ========================================================================

    public static final String CODE_SKELETON = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_code_skeleton\","
            + "    \"description\": \"Return the code skeleton: imports/setup, shared definitions, and structural scaffolding.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"headerCode\": { \"type\": \"string\", \"description\": \"Complete skeleton code\" }"
            + "      },"
            + "      \"required\": [\"headerCode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    public static final String SCENE_CODE = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_scene_code\","
            + "    \"description\": \"Return the implementation code for a single scene section.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"sceneCode\": { \"type\": \"string\", \"description\": \"Complete method code for this scene\" },"
            + "        \"sceneMethodName\": { \"type\": \"string\", \"description\": \"Method name for this scene\" }"
            + "      },"
            + "      \"required\": [\"sceneCode\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";

    // ========================================================================

    public static final String CODE_REVIEW = "["
            + "{"
            + "  \"type\": \"function\","
            + "  \"function\": {"
            + "    \"name\": \"write_code_review\","
            + "    \"description\": \"Return structured storyboard-alignment review for Manim or GeoGebra output quality.\","
            + "    \"parameters\": {"
            + "      \"type\": \"object\","
            + "      \"properties\": {"
            + "        \"approved_for_render\": { \"type\": \"boolean\", \"description\": \"Whether code is approved for render\" },"
            + "        \"layout_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"continuity_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"pacing_score\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"clutter_risk\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"likely_offscreen_risk\": { \"type\": \"integer\", \"minimum\": 1, \"maximum\": 10 },"
            + "        \"summary\": { \"type\": \"string\" },"
            + "        \"strengths\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "        \"blocking_issues\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } },"
            + "        \"revision_directives\": { \"type\": \"array\", \"items\": { \"type\": \"string\" } }"
            + "      },"
            + "      \"required\": [\"approved_for_render\", \"layout_score\", \"continuity_score\", \"pacing_score\"]"
            + "    }"
            + "  }"
            + "}"
            + "]";
}
