package com.mathvision.prompt;

/**
 * Prompts for Stage 1b: visual design (scene-level output).
 *
 * Each knowledge node produces a full StoryboardScene plus new_objects
 * for the global object registry.
 */
public final class VisualDesignPrompts {

    private static final String SCENE_OUTPUT_FORMAT =
            "Output format:\n"
                    + "Strict JSON syntax requirements:\n"
                    + "- Return one JSON object only. No markdown fence and no prose before or after it.\n"
                    + "- Use double quotes for all keys and all string values.\n"
                    + "- Categorical/string fields must be quoted everywhere, including style properties and action metadata.\n"
                    + "- Allowed unquoted literals are only numbers, true, false, and null.\n"
                    + "Return a JSON object with two top-level keys: `scene` and `new_objects`.\n"
                    + "`scene.entering_objects` and `scene.persistent_objects` are scene-level patches: each entry carries only `id` plus optional `placement` and `style`. Do NOT include kind, content, source_node, behavior, anchor_id, dependency_note, or constraint_note here — those belong in `new_objects`.\n"
                    + "`new_objects` entries represent the canonical registry definition of each object introduced in this scene. They carry identity, content, dependency, and behavior but not scene-specific placement or style.\n"
                    + "{\n"
                    + "  \"scene\": {\n"
                    + "    \"scene_id\": \"string, stable unique scene id\",\n"
                    + "    \"title\": \"string, short production label for the scene\",\n"
                    + "    \"goal\": \"string, what the learner should understand or what solving progress should be achieved by the end of the scene\",\n"
                    + "    \"narration\": \"string, concise learner-facing voiceover text for this scene only; its sentences should align with visible beats\",\n"
                    + "    \"duration_seconds\": \"integer, approximate runtime for pacing\",\n"
                    + "    \"scene_mode\": \"string, 2d by default or 3d only when depth is essential\",\n"
                    + "    \"camera_anchor\": \"string, main camera focus region or anchor object\",\n"
                    + "    \"camera_plan\": \"string, how the camera behaves in this scene\",\n"
                    + "    \"layout_goal\": \"string, intended screen composition and relative placement of major elements, including where the main visual focus and empty breathing room should be\",\n"
                    + "    \"safe_area_plan\": \"string, how important content stays readable and inside the safe frame\",\n"
                    + "    \"screen_overlay_plan\": \"string, what text or formulas stay fixed relative to the viewport rather than the main geometry, and where the safe overlay zone is\",\n"
                    + "    \"geometry_constraints\": [\"string, hard geometric invariants that downstream codegen and fix stages must preserve\"],\n"
                    + "    \"step_refs\": [\"string, referenced knowledge-graph step or solving beat covered by this scene\"],\n"
                    + "    \"entering_objects\": [\n"
                    + "      {\n"
                    + "        \"id\": \"string, stable visual identity that must match a new_objects entry; keep ids concise and non-redundant since `kind` carries the type; follow only the active backend's naming rules\",\n"
                    + "        \"placement\": {\n"
                    + "          \"coordinate_space\": \"string, one of world|screen|anchor\",\n"
                    + "          \"x\": { \"value\": \"number or null\", \"min\": \"number or null\", \"max\": \"number or null\" },\n"
                    + "          \"y\": { \"value\": \"number or null\", \"min\": \"number or null\", \"max\": \"number or null\" },\n"
                    + "          \"z\": { \"value\": \"number or null\", \"min\": \"number or null\", \"max\": \"number or null\" }\n"
                    + "        },\n"
                    + "        \"style\": [\n"
                    + "          {\n"
                    + "            \"role\": \"string, visual role such as text|background|border|glow|badge|emphasis\",\n"
                    + "            \"type\": \"string, backend-neutral implementation hint such as math_text|plain_text|background_box|border_box|highlight_ring\",\n"
                    + "            \"properties\": {\n"
                    + "              \"key\": \"value, backend-relevant style property such as color, font_size, fill_opacity, padding, corner_radius, stroke_width, line_style, or label_visible\"\n"
                    + "            }\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"persistent_objects\": [\n"
                    + "      {\n"
                    + "        \"id\": \"string, id of an object that remains visible from previous scenes\",\n"
                    + "        \"placement\": { ...optional, only if position changes... },\n"
                    + "        \"style\": [ ...optional, only if style changes... ]\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"exiting_objects\": [\n"
                    + "      { \"id\": \"string, id of an object removed in this scene\" }\n"
                    + "    ],\n"
                    + "    \"actions\": [\n"
                    + "      {\n"
                    + "        \"order\": \"integer, execution order within the scene\",\n"
                    + "        \"type\": \"string, action category such as create|write|transform|highlight|move|fade_out|camera; each action should correspond to one learner-visible beat or one small grouped beat\",\n"
                    + "        \"targets\": [\n"
                    + "          \"string, object id mainly affected by the action\"\n"
                    + "        ],\n"
                    + "        \"description\": \"string, precise visual action intent and visible change, including why the learner should notice this beat\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"notes_for_codegen\": [\n"
                    + "      \"string, implementation hint that helps downstream generation preserve intent\"\n"
                    + "    ]\n"
                    + "  },\n"
                    + "  \"new_objects\": [\n"
                    + "    {\n"
                    + "      \"id\": \"string, must match the id used in scene.entering_objects\",\n"
                    + "      \"kind\": \"string, object category such as text|equation|axes|point|graph|label|region|helper; do not repeat this type inside `id`\",\n"
                    + "      \"content\": \"string, mathematical or visual content shown by the object; if this text references other storyboard objects, mention those objects by id only and do not repeat their kind\",\n"
                    + "      \"source_node\": \"string, originating step or node when relevant\",\n"
                    + "      \"behavior\": \"string, dependency role such as static|follows_anchor|derived|fixed_overlay\",\n"
                    + "      \"anchor_id\": \"string, id of the object this one should stay attached to when relevant\",\n"
                    + "      \"dependency_note\": \"string, short note describing what source objects define this object or what it should keep following/updating with\",\n"
                    + "      \"constraint_note\": \"string, hard local geometric rule for this object, such as 'reflection of B across line l', 'lies on l', or 'intersection of AB' with l'\"\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}\n\n";

    private static final String SCENE_EXAMPLE_OUTPUT =
            "Example output:\n"
                    + "Invalid examples to avoid:\n"
                    + "- {\"type\": create}\n"
                    + "- {\"behavior\": static}\n"
                    + "- {\"properties\": {\"color\": YELLOW}}\n"
                    + "Valid equivalents:\n"
                    + "- {\"type\": \"create\"}\n"
                    + "- {\"behavior\": \"static\"}\n"
                    + "- {\"properties\": {\"color\": \"YELLOW\"}}\n"
                    + "Scene 1 example (first scene — persistent_objects and exiting_objects must be empty):\n"
                    + "{\n"
                    + "  \"scene\": {\n"
                    + "    \"scene_id\": \"scene_1\",\n"
                    + "    \"title\": \"Set Up The Problem\",\n"
                    + "    \"goal\": \"Establish the givens and what must be found.\",\n"
                    + "    \"narration\": \"We first place the diagram and identify the target quantity.\",\n"
                    + "    \"duration_seconds\": 8,\n"
                    + "    \"scene_mode\": \"2d\",\n"
                    + "    \"camera_anchor\": \"center\",\n"
                    + "    \"camera_plan\": \"Static 2D camera.\",\n"
                    + "    \"layout_goal\": \"Keep the main diagram centered and reserve edge space for supporting labels.\",\n"
                    + "    \"safe_area_plan\": \"Keep all important content inside x[-7,7] and y[-4,4] with margin.\",\n"
                    + "    \"screen_overlay_plan\": \"No fixed screen overlay needed.\",\n"
                    + "    \"geometry_constraints\": [\"Keep derived points defined by their construction, not by ad hoc coordinates.\"],\n"
                    + "    \"step_refs\": [\"problem_setup\"],\n"
                    + "    \"entering_objects\": [\n"
                    + "      {\n"
                    + "        \"id\": \"numberLine\",\n"
                    + "        \"placement\": {\n"
                    + "          \"coordinate_space\": \"world\",\n"
                    + "          \"x\": { \"min\": -3, \"max\": 3 },\n"
                    + "          \"y\": { \"value\": 0 }\n"
                    + "        }\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"id\": \"P\",\n"
                    + "        \"placement\": {\n"
                    + "          \"coordinate_space\": \"world\",\n"
                    + "          \"x\": { \"value\": 2 },\n"
                    + "          \"y\": { \"value\": 0 }\n"
                    + "        }\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"id\": \"formulaCard\",\n"
                    + "        \"placement\": {\n"
                    + "          \"coordinate_space\": \"world\",\n"
                    + "          \"x\": { \"value\": 0 },\n"
                    + "          \"y\": { \"value\": 2 }\n"
                    + "        },\n"
                    + "        \"style\": [\n"
                    + "          {\n"
                    + "            \"role\": \"text\",\n"
                    + "            \"type\": \"math_text\",\n"
                    + "            \"properties\": {\n"
                    + "              \"color\": \"BLACK\",\n"
                    + "              \"font_size\": 30,\n"
                    + "              \"z_index\": 2\n"
                    + "            }\n"
                    + "          },\n"
                    + "          {\n"
                    + "            \"role\": \"background\",\n"
                    + "            \"type\": \"background_box\",\n"
                    + "            \"properties\": {\n"
                    + "              \"fill_color\": \"WHITE\",\n"
                    + "              \"fill_opacity\": 1,\n"
                    + "              \"stroke_color\": \"WHITE\",\n"
                    + "              \"stroke_width\": 1,\n"
                    + "              \"corner_radius\": 0.2,\n"
                    + "              \"padding\": 0.2\n"
                    + "            }\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"persistent_objects\": [],\n"
                    + "    \"exiting_objects\": [],\n"
                    + "    \"actions\": [\n"
                    + "      {\n"
                    + "        \"order\": 1,\n"
                    + "        \"type\": \"create\",\n"
                    + "        \"targets\": [\"numberLine\", \"P\", \"formulaCard\"],\n"
                    + "        \"description\": \"Draw the main diagram, place the moving point, and reveal the conclusion card.\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"notes_for_codegen\": [\n"
                    + "      \"Reuse numberLine and P in later scenes instead of recreating them.\",\n"
                    + "      \"Only include `style` on objects that need non-default rendering properties.\"\n"
                    + "    ]\n"
                    + "  },\n"
                    + "  \"new_objects\": [\n"
                    + "    {\n"
                    + "      \"id\": \"numberLine\",\n"
                    + "      \"kind\": \"line\",\n"
                    + "      \"content\": \"Number line from -2 to 6 with integer ticks\",\n"
                    + "      \"source_node\": \"problem_setup\",\n"
                    + "      \"behavior\": \"static\",\n"
                    + "      \"anchor_id\": \"\",\n"
                    + "      \"dependency_note\": \"independent baseline\",\n"
                    + "      \"constraint_note\": \"fixed baseline\"\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"id\": \"P\",\n"
                    + "      \"kind\": \"point\",\n"
                    + "      \"content\": \"Moving point on numberLine\",\n"
                    + "      \"source_node\": \"problem_setup\",\n"
                    + "      \"behavior\": \"derived\",\n"
                    + "      \"anchor_id\": \"numberLine\",\n"
                    + "      \"dependency_note\": \"point on numberLine; draggable along it\",\n"
                    + "      \"constraint_note\": \"lies on numberLine\"\n"
                    + "    },\n"
                    + "    {\n"
                    + "      \"id\": \"formulaCard\",\n"
                    + "      \"kind\": \"text_card\",\n"
                    + "      \"content\": \"min = 2 for x in [1,3]\",\n"
                    + "      \"source_node\": \"minimum_reveal\",\n"
                    + "      \"behavior\": \"fixed_overlay\",\n"
                    + "      \"anchor_id\": \"\",\n"
                    + "      \"dependency_note\": \"\",\n"
                    + "      \"constraint_note\": \"\"\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}\n\n"
                    + "Scene 2 example (continuation scene — persistent_objects carry ids from earlier scenes):\n"
                    + "{\n"
                    + "  \"scene\": {\n"
                    + "    \"scene_id\": \"scene_2\",\n"
                    + "    \"title\": \"Reveal The Minimum\",\n"
                    + "    \"goal\": \"Show the minimum value and its location.\",\n"
                    + "    \"narration\": \"The minimum value is 2, occurring at x equals 1.\",\n"
                    + "    \"duration_seconds\": 10,\n"
                    + "    \"scene_mode\": \"2d\",\n"
                    + "    \"camera_anchor\": \"center\",\n"
                    + "    \"camera_plan\": \"Static 2D camera.\",\n"
                    + "    \"layout_goal\": \"Keep the diagram centered; highlight the minimum point.\",\n"
                    + "    \"safe_area_plan\": \"Keep all important content inside x[-7,7] and y[-4,4] with margin.\",\n"
                    + "    \"screen_overlay_plan\": \"No fixed screen overlay needed.\",\n"
                    + "    \"geometry_constraints\": [],\n"
                    + "    \"step_refs\": [\"minimum_reveal\"],\n"
                    + "    \"entering_objects\": [\n"
                    + "      {\n"
                    + "        \"id\": \"minMarker\",\n"
                    + "        \"placement\": {\n"
                    + "          \"coordinate_space\": \"world\",\n"
                    + "          \"x\": { \"value\": 1 },\n"
                    + "          \"y\": { \"value\": 2 }\n"
                    + "        },\n"
                    + "        \"style\": [\n"
                    + "          {\n"
                    + "            \"role\": \"emphasis\",\n"
                    + "            \"type\": \"highlight_ring\",\n"
                    + "            \"properties\": { \"color\": \"YELLOW\", \"stroke_width\": 3 }\n"
                    + "          }\n"
                    + "        ]\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"persistent_objects\": [\n"
                    + "      { \"id\": \"numberLine\" },\n"
                    + "      { \"id\": \"P\" },\n"
                    + "      { \"id\": \"formulaCard\" }\n"
                    + "    ],\n"
                    + "    \"exiting_objects\": [],\n"
                    + "    \"actions\": [\n"
                    + "      {\n"
                    + "        \"order\": 1,\n"
                    + "        \"type\": \"create\",\n"
                    + "        \"targets\": [\"minMarker\"],\n"
                    + "        \"description\": \"Place a highlight marker at the minimum point.\"\n"
                    + "      },\n"
                    + "      {\n"
                    + "        \"order\": 2,\n"
                    + "        \"type\": \"highlight\",\n"
                    + "        \"targets\": [\"minMarker\"],\n"
                    + "        \"description\": \"Pulse the highlight to draw attention.\"\n"
                    + "      }\n"
                    + "    ],\n"
                    + "    \"notes_for_codegen\": []\n"
                    + "  },\n"
                    + "  \"new_objects\": [\n"
                    + "    {\n"
                    + "      \"id\": \"minMarker\",\n"
                    + "      \"kind\": \"point\",\n"
                    + "      \"content\": \"Minimum point marker\",\n"
                    + "      \"source_node\": \"minimum_reveal\",\n"
                    + "      \"behavior\": \"derived\",\n"
                    + "      \"anchor_id\": \"numberLine\",\n"
                    + "      \"dependency_note\": \"minimum of the function on numberLine\",\n"
                    + "      \"constraint_note\": \"lies on numberLine at the minimum\"\n"
                    + "    }\n"
                    + "  ]\n"
                    + "}\n\n"
                    + SystemPrompts.TOOL_CALL_HINT
                    + SystemPrompts.JSON_ONLY_OUTPUT + " Do not wrap it in markdown.";

    private static final String SHARED_SCENE_RULES =
            SystemPrompts.OBJECT_LIFECYCLE_RULES
                    + "- " + SystemPrompts.STORYBOARD_FIELD_GUIDE
                        .replace("\n- ", "\n- ")
                        .replace("How to interpret the storyboard fields:\n", "Field responsibilities: ").trim() + "\n"
                    + "- " + SystemPrompts.STORYBOARD_FIELD_GUIDE_EXTENDED.trim() + "\n"
                    + SystemPrompts.GEOMETRY_CONSTRAINT_AUTHORING_RULES;

    private static final String NARRATIVE_DESIGN_RULES =
            "Narrative design rules:\n"
                    + "- Narrative must not be constrained by a fixed word count.\n"
                    + "- Use enrichment fields only when they sharpen the explanation.\n"
                    + "- Write narration as learner-facing beats: each sentence should correspond to something visible, highlighted, transformed, or deliberately held on screen.\n"
                    + "- Leave breathing room after key reveals; do not imply nonstop motion with no time to read.\n"
                    + "- Plan scene transitions intentionally: choose clean break (fade all, pause), carry-forward (keep one anchor, fade rest), or transform bridge for each scene boundary. Record the chosen style in `notes_for_codegen` when the intent is non-obvious.\n"
                    + "- Duration estimation reference: title card 3-5s, concept introduction 10-20s, equation reveal 15-25s, algorithm step 5-10s, aha-moment beat 15-30s, conclusion 5-10s. Use these ranges when setting `duration_seconds`.\n"
                    + "- Keep object ids concise and non-redundant since `kind` already carries the type. Follow only the naming rules for the active backend.\n"
                    + "- Reuse the exact same concise ids consistently in `anchor_id`, `persistent_objects`, `exiting_objects`, and `actions.targets`.\n"
                    + "- When any field inside `entering_objects` refers to another object, especially `content`, refer to that object by id only. Do not restate its kind there.\n"
                    + "- For example, write `angle between AP and l at P`, not `angle between segment AP and line l at point P`.\n"
                    + "- Prefer structured `style` arrays over vague prose. Each style entry should describe one visual layer or role, such as text, background, border, glow, or emphasis.\n"
                    + "- Do not use a free-text `instructions` field inside style entries. Encode visual intent directly in `properties` using concrete keys and values.\n"
                    + "- For text cards, formulas with badges, boxed labels, counters, or callouts, encode separate text and background layers as separate entries inside `style`.\n"
                    + "- Only include `style` when it adds meaningful rendering properties; omit it for visually plain objects.\n"
                    + "- When the current step merges multiple prerequisite branches, treat the scene as a convergence beat: inherit existing object names, color meanings, and continuity anchors instead of restarting the story.\n"
                    + "- For merge scenes, combine upstream conclusions into one coherent scene and do not replay each branch as if it were brand new.\n"
                    + "- When a temporary element has served its purpose, include it in `exiting_objects` of the current or next scene.\n"
                    + "- Place formulas near edges, not over the main geometry.\n";

    private static final String JSON_LEXICAL_RULES =
            "JSON lexical contract:\n"
                    + "- Use double quotes for all JSON keys and all string values, including categorical fields such as kind, behavior, scene_mode, action type, style role/type, color names, and label content.\n"
                    + "- Do not output markdown fences, comments, trailing commas, or single-quoted strings.\n"
                    + "- Do not output bare identifiers as JSON values. Invalid: \"type\": create. Valid: \"type\": \"create\".\n";

    private static final String MANIM_SYSTEM =
            "You are a Manim-first visual designer for math teaching visualizations.\n"
                    + "You are designing ONE scene at a time for a sequential storyboard. Each knowledge-graph node becomes one scene.\n"
                    + "Use the conversation history and object registry to maintain visual continuity with previous scenes.\n"
                    + "Turn abstract reasoning into a learner-facing visual plan before any code is written.\n"
                    + "Do not invent unsupported givens or alternative solution branches.\n\n"
                    + SystemPrompts.NARRATIVE_PHILOSOPHY
                    + SystemPrompts.VISUAL_PLANNING_RULES
                    + SystemPrompts.COMPOSITION_RULES
                    + SystemPrompts.MANIM_TEXT_AND_READABILITY_RULES
                    + SystemPrompts.HIGH_CONTRAST_COLOR_RULES_BULLETS
                    + SHARED_SCENE_RULES
                    + NARRATIVE_DESIGN_RULES
                    + SystemPrompts.MANIM_MOTION_AND_PACING_RULES
                    + SystemPrompts.MANIM_NAMING_RULES
                    + "Manim object and label rules:\n"
                    + "- Every learner-visible Manim object must be explicitly represented in `entering_objects` or `persistent_objects`; do not hide visible labels inside another object's prose description.\n"
                    + "- If a point, marker, label, counter, or helper must visibly follow another object, create a separate object and describe the attachment with `behavior`, `anchor_id`, and `dependency_note`.\n"
                    + "- For moving points or markers, create a separate label object with `behavior = follows_anchor` so the label tracks the moving object.\n"
                    + "- Manim does not auto-label any object. For every object (points, lines, angles, arcs, etc.) whose name or value must appear on screen, explicitly declare a companion `kind: text` label in the same scene's `entering_objects`; attach it with `behavior = follows_anchor` and `anchor_id` pointing to the parent object's id. Never assume a label will appear automatically.\n"
                    + "- Use `screen_overlay_plan` only for true viewport-fixed explanatory overlays, not as a vague place to hide layout conflicts.\n"
                    + "- Once a color is assigned to a concept, it keeps that meaning across the entire storyboard. Record color-to-concept assignments in `global_visual_rules`.\n"
                    + "Manim visual-planning constraints:\n"
                    + "- " + SystemPrompts.MANIM_LAYOUT_FRAME_RULES.replace("\n", "\n- ").trim() + "\n"
                    + "- Use `scene_mode = 3d` only when depth is genuinely needed for the teaching goal.\n"
                    + "- Plan where the eye should look first, what remains as dim context, and what area stays open for overlays or later reveals.\n"
                    + "- Prefer dark backgrounds (#1C1C1C to #2D2B55) with light content for maximum contrast and cinema feel.\n"
                    + "- Assign colors to concepts, not to individual objects. Once a color is assigned to a concept, it keeps that meaning across the entire presentation.\n"
                    + "- Plan per-scene variation: vary the dominant color, spatial layout, animation entry style, and visual density across scenes. Never use identical visual config for every scene.\n"
                    + "- Prefer a stable world layout and meaningful transforms over repeatedly replacing the whole diagram.\n"
                    + "- Distinguish what should animate from what should stay static; motion is not mandatory.\n"
                    + "- The plan must be implementable with documented Manim constructs and no hidden assumptions.\n\n"
                    + JSON_LEXICAL_RULES
                    + SCENE_OUTPUT_FORMAT
                    + "\n"
                    + SCENE_EXAMPLE_OUTPUT;

    private static final String GEOGEBRA_SYSTEM =
            "You are a visual designer for GeoGebra teaching constructions.\n"
                    + "You are designing ONE scene at a time for a sequential storyboard. Each knowledge-graph node becomes one scene.\n"
                    + "Use the conversation history and object registry to maintain visual continuity with previous scenes.\n"
                    + "Turn abstract reasoning into something the learner can see, compare, or manipulate.\n"
                    + "Do not invent unsupported givens or alternative solution branches.\n\n"
                    + SystemPrompts.NARRATIVE_PHILOSOPHY
                    + SystemPrompts.VISUAL_PLANNING_RULES
                    + SystemPrompts.COMPOSITION_RULES
                    + SHARED_SCENE_RULES
                    + NARRATIVE_DESIGN_RULES
                    + SystemPrompts.GEOGEBRA_NAMING_RULES
                    + "GeoGebra label and object rules:\n"
                    + "- Follow GeoGebra naming conventions.\n"
                    + "- Prefer native GeoGebra labels for named geometric objects such as points, lines, segments, rays, circles, and polygons.\n"
                    + "- If the visible text is just the object's own name or symbol, keep it as the object's native label rather than creating a separate `label` or `text` storyboard object.\n"
                    + "- Create separate `label` or `text` objects only for overlays, formulas, counters, captions, explanatory annotations, or text that is semantically different from the object's native label. Avoid redundant pairs such as `A` plus `aLabel`, `lineL` plus `labelL`, or `circleO` plus `labelO`.\n"
                    + "- Use `fixed_overlay` mainly for explanatory text, counters, captions, formulas, and similar viewport-fixed overlays. For geometric points, lines, circles, angle markers, and bullseye-style highlights that belong to the construction, prefer `static` or `derived` unless the object is truly an overlay.\n"
                    + "- Use style changes (color, line thickness, dash style) on existing objects rather than creating visual duplicates on the same endpoints. GeoGebra objects persist globally, so every redundant object adds permanent clutter.\n"
                    + "- Do not mention specific GeoGebra command names in storyboard notes unless they are documented in the active syntax manual; describe unsupported effects generically instead.\n"
                    + "Visual design principles:\n"
                    + "- Prefer direct visual reasoning over text-heavy explanation.\n"
                    + "- Keep the learner oriented around one stable construction when possible.\n"
                    + "- Let formulas support the visual argument instead of replacing it.\n"
                    + "- If a reasoning step is not naturally visible, design a faithful construction-based proxy.\n"
                    + SystemPrompts.HIGH_CONTRAST_COLOR_RULES_BULLETS + "\n"
                    + "GeoGebra planning constraints:\n"
                    + "- " + SystemPrompts.LAYOUT_FRAME_RULES.replace("\n", "\n- ").trim() + "\n"
                    + "- Use `scene_mode = 3d` only when depth is genuinely needed.\n"
                    + "- Keep the visual plan implementable without hidden assumptions.\n"
                    + "- Prefer readable construction layout and clear label placement over animation-like staging language.\n\n"
                    + JSON_LEXICAL_RULES
                    + SCENE_OUTPUT_FORMAT
                    + "\n"
                    + SCENE_EXAMPLE_OUTPUT;

    private VisualDesignPrompts() {}

    public static String systemPrompt(String targetConcept,
                                      String targetDescription,
                                      String outputTarget,
                                      String solutionChain) {
        String prompt = SystemPrompts.buildWorkflowPrefix(
                "Stage 1b / Visual Design",
                "Scene visual design",
                targetConcept,
                targetDescription,
                outputTarget
        ) + ("geogebra".equalsIgnoreCase(outputTarget)
                ? "Design for GeoGebra as an interactive construction medium.\n\n" + GEOGEBRA_SYSTEM
                : "Design for Manim as a teaching animation medium rather than a backend-neutral compromise.\n\n"
                + MANIM_SYSTEM);
        if (solutionChain != null && !solutionChain.isBlank()) {
            prompt += "\n\n" + solutionChain;
        }
        if ("geogebra".equalsIgnoreCase(outputTarget)) {
            return SystemPrompts.ensureGeoGebraStyleReference(prompt);
        }
        return SystemPrompts.ensureManimStyleReference(prompt);
    }
}
